export async function getDasboardData() {
    //według AI tak moge zasymulować prawdziwe API więc sie nie kłóciłem ¯\_(ツ)_/¯
    await new Promise((res) => setTimeout(res, 600));

    return {
        stats: {
            revenue: "78,500",
            users: "8,421",
            orders: "3,925",
            conversion: "27,4%",
        },
        activity: [
            "New user registered",
            "Order #1042 completed",
            "Payment received",
            "System backup finished",
            "New subscription started",
            "User upgraded plan",
            "Order #1043 completed",
            "System cache cleared",
            "Payment failed",
            "New user registered",
            "Database optimized",
            "Refund processed",
            "Order #1044 completed",
            "System cache cleared",
            "New subscription started",
            "New subscription started",
            "Payment received",
            "User downgraded plan",
            "Order #1045 completed",
            "New user registered",
            "New user registered",
            "Security scan completed",
            "Payment received",
            "Database optimized",
            "Payment received",
            "Order #1046 completed",
            "New subscription started",
            "User logged in",
            "System backup finished",
            "Order #1047 completed",
        ],
        news: [
            "AI insights module deployed successfully",
            "Weekly sales report is ready",
            "3 new support tickets assigned",
            "Marketing campaign reached 12k users",
            "Inventory sync completed",
            "Server response time improved by 18%",
            "New partner integration available",
            "Finance dashboard updated",
            "2FA enabled for all admin accounts",
            "Customer satisfaction score increased",
            "Cloud storage usage reached 72%",
            "Monthly revenue target achieved",
            "New analytics widgets added",
            "Background jobs processed successfully",
            "SEO performance improved this week",
            "New team member joined the workspace",
            "Application uptime stable at 99.98%",
            "Security audit completed successfully",
            "New comments awaiting moderation",
            "Subscription renewals processed",
            "Mobile app version 2.4 released",
            "API latency reduced across regions",
            "New invoices generated automatically",
            "Traffic spike detected from social media",
            "User activity increased by 24%",
            "Scheduled maintenance completed",
            "Customer onboarding flow updated",
            "Data export finished successfully",
            "Real-time monitoring enabled",
            "Workspace settings synchronized",
        ],
        chart: [
            { name: "D1", revenue: 0 },
            { name: "D2", revenue: 1000 },
            { name: "D3", revenue: 500 },
            { name: "D4", revenue: 1500 },
            { name: "D5", revenue: 500 },
            { name: "D6", revenue: 2000 },
            { name: "D7", revenue: 1500 },
            { name: "D8", revenue: 3000 },
            { name: "D9", revenue: 1000 },
            { name: "D10", revenue: 2000 },
            { name: "D11", revenue: 500 },
            { name: "D12", revenue: 1500 },
            { name: "D13", revenue: 500 },
            { name: "D14", revenue: 1500 },
            { name: "D15", revenue: 1000 },
            { name: "D16", revenue: 1500 },
            { name: "D17", revenue: 1000 },
            { name: "D18", revenue: 1500 },
            { name: "D19", revenue: 1000 },
            { name: "D20", revenue: 2000 },
            { name: "D21", revenue: 500 },
            { name: "D22", revenue: 2500 },
            { name: "D23", revenue: 1500 },
            { name: "D24", revenue: 2000 },
            { name: "D25", revenue: 1500 },
            { name: "D26", revenue: 2500 },
            { name: "D27", revenue: 1000 },
            { name: "D28", revenue: 2000 },
            { name: "D29", revenue: 500 },
            { name: "D30", revenue: 1500 },
            { name: "D31", revenue: 500 },
            { name: "D32", revenue: 1000 },
            { name: "D33", revenue: 500 },
            { name: "D34", revenue: 1000 },
            { name: "D35", revenue: 500 },
            { name: "D36", revenue: 2000 },
            { name: "D37", revenue: 1000 },
            { name: "D38", revenue: 2500 },
            { name: "D39", revenue: 1500 },
            { name: "D40", revenue: 2500 },
            { name: "D41", revenue: 1500 },
            { name: "D42", revenue: 4000 },
            { name: "D43", revenue: 2000 },
            { name: "D44", revenue: 3500 },
            { name: "D45", revenue: 2000 },
            { name: "D46", revenue: 3000 },
            { name: "D47", revenue: 2500 },
            { name: "D48", revenue: 3000 },
            { name: "D49", revenue: 1500 },
            { name: "D50", revenue: 4000 },
        ]
    };
}